name: CI Test & Deploy

on:
  push:
    branches:
      - actions_test_student6

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: echo "✅ Tests passed successfully!"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Application
        run: echo "✅ App deployed successfully!"
