name: Fake CI/CD Demo

on:
  push:
    branches:
      - actions_test_student6

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run fake tests
        run: echo "Tests passed!"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Fake deploy
        run: echo "App deployed successfully!"
